---
- name: create /var/www/ directory
  file:
    dest: /var/www/
    state: directory
    owner: www-data
    group: www-data
    mode: 0700

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart php7.0-fpm
    - restart nginx

- name: Copy public key into docroot
  authorized_key:
    user: www-data
    key: "{{ lookup('file', 'deploykey.pub') }}"

- name: Set www-data user shell
  user:
    name: www-data
    shell: /bin/bash
