---
- name: Ensure php7.0-fpm cgi.fix_pathinfo=0
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: '^(.*)cgi.fix_pathinfo='
    line: cgi.fix_pathinfo=0
  notify:
    - restart php7.0-fpm
    - restart nginx

- name: enable php7.0 mcrypt module
  shell: phpenmod mcrypt
  args:
    creates: /etc/php/7.0/cli/conf.d/20-mcrypt.ini
